# Generated by Django 5.2.5 on 2025-10-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='summary',
            new_name='author',
        ),
    ]
