# Generated by Django 5.2.5 on 2025-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_rename_summary_student_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
