# Generated by Django 5.2.5 on 2025-10-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_delete_book'),
        ('subapp', '0003_student_ending_date_student_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.useraccount'),
        ),
    ]
