# Generated by Django 5.2.5 on 2025-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
