# Generated by Django 5.2.5 on 2025-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_useraccount_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
