# Generated by Django 5.2.5 on 2025-10-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
